name: replication-environment
channels:
  - conda-forge
#  - r
#  - defaults
dependencies:
  - python==3.8
  - numpy
#  - bokeh
#  - dill
#  - dask
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - linearmodels
  - matplotlib
  - pandas
  - pandasql
  - partd
  - psutil
  - r
#  - rstudio
  - r-base
  - r-irkernel
  - sympy
  - rpy2
  - r-tidyr
  - r-tibble
  - r-dplyr
  - scipy
  - statsmodels
  - seaborn
  - scikit-learn
  - toolz
  - pip
  - pandas-datareader
  - pip:
      - googledrivedownloader
      - pandas_datareader
      - nbgitpuller
